/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bbdd_Zoo_Interfaz;

import Utilidades.TextPrompt;
import java.awt.Color;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.JOptionPane;

/**
 *
 * @author Ismael
 */
public class frame_Trabajos extends javax.swing.JFrame {

    private int x;
    private int y;

    /**
     * Creates new form frame_Trabajos
     */
    public frame_Trabajos() {
        initComponents();
        TextPrompt placeholcer = new TextPrompt("Trabajo a realizar:", jTNombreTrabajo);
    }

    public void insertTrabajo() {

        String nombre = jTNombreTrabajo.getText();

        DBManagerZoo.insertTrabajo(nombre);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBguardarTrabajo = new javax.swing.JButton();
        jTNombreTrabajo = new javax.swing.JTextField();
        jButtonAtrasNuevoTrabajo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Jurassic Park", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nueva Trabajo");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Trabajo");

        jBguardarTrabajo.setBackground(new java.awt.Color(113, 0, 3));
        jBguardarTrabajo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jBguardarTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        jBguardarTrabajo.setText("Guardar");
        jBguardarTrabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBguardarTrabajoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBguardarTrabajoMouseExited(evt);
            }
        });
        jBguardarTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarTrabajoActionPerformed(evt);
            }
        });

        jTNombreTrabajo.setBackground(new java.awt.Color(255, 255, 255));
        jTNombreTrabajo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTNombreTrabajo.setForeground(new java.awt.Color(0, 0, 0));
        jTNombreTrabajo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jButtonAtrasNuevoTrabajo.setBackground(new java.awt.Color(103, 0, 3));
        jButtonAtrasNuevoTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Imagen/hacia-atras (1).png"))); // NOI18N
        jButtonAtrasNuevoTrabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAtrasNuevoTrabajoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAtrasNuevoTrabajoMouseExited(evt);
            }
        });
        jButtonAtrasNuevoTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasNuevoTrabajoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(jTNombreTrabajo)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jBguardarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAtrasNuevoTrabajo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAtrasNuevoTrabajo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 123, Short.MAX_VALUE)
                        .addComponent(jBguardarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTNombreTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBguardarTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarTrabajoActionPerformed

        if (jTNombreTrabajo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "no puede dejar el campo vacío");
        } else {
            insertTrabajo();
            dispose();
        }
    }//GEN-LAST:event_jBguardarTrabajoActionPerformed

    private void jButtonAtrasNuevoTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasNuevoTrabajoActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonAtrasNuevoTrabajoActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_formMouseDragged

    private void jButtonAtrasNuevoTrabajoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasNuevoTrabajoMouseEntered
        jButtonAtrasNuevoTrabajo.setCursor(new Cursor(HAND_CURSOR));
        jButtonAtrasNuevoTrabajo.setBackground( new Color(217,165,9));
        jButtonAtrasNuevoTrabajo.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButtonAtrasNuevoTrabajoMouseEntered

    private void jButtonAtrasNuevoTrabajoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAtrasNuevoTrabajoMouseExited
        jButtonAtrasNuevoTrabajo.setBackground( new Color(103,0,3));
        jButtonAtrasNuevoTrabajo.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonAtrasNuevoTrabajoMouseExited

    private void jBguardarTrabajoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBguardarTrabajoMouseEntered
        jBguardarTrabajo.setCursor(new Cursor(HAND_CURSOR));
        jBguardarTrabajo.setBackground( new Color(217,165,9));
        jBguardarTrabajo.setForeground(Color.BLACK);
    }//GEN-LAST:event_jBguardarTrabajoMouseEntered

    private void jBguardarTrabajoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBguardarTrabajoMouseExited
        jBguardarTrabajo.setBackground( new Color(103,0,3));
        jBguardarTrabajo.setForeground(Color.WHITE);
    }//GEN-LAST:event_jBguardarTrabajoMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frame_Trabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frame_Trabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frame_Trabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frame_Trabajos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frame_Trabajos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBguardarTrabajo;
    private javax.swing.JButton jButtonAtrasNuevoTrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTNombreTrabajo;
    // End of variables declaration//GEN-END:variables
}
