/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bbdd_Zoo_Interfaz;

import bbdd_Zoo_Interfaz.DBManagerZoo;
import java.awt.Color;
import java.awt.Cursor;
import static java.awt.Frame.DEFAULT_CURSOR;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.MouseInfo;
import java.awt.Point;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ismael
 */
public class Panel_Visitante extends javax.swing.JFrame {

    private int x;
    private int y;
    /**
     * Creates new form Panel_Visitante
     */
    public Panel_Visitante(String dni) {
        initComponents();
        DBManagerZoo.loadDriver();
        DBManagerZoo.connect();
        rellenarTablaVisitantes();

        UIManager Ui = new UIManager();
        Ui.put("nimbusBlueGrey", new ColorUIResource(103, 0, 3));
        jTablePanelVisitante.getTableHeader().setForeground(Color.white);
        
        String name = DBManagerZoo.getNameLogin(dni);
        jLabelUsuarioSesion.setText(dni + " - " + name);
    }
    
    // Configuración de la tabla Animals
    private static final String DB_ANIMALS = "ANIMALS";
    private static final String DB_ANIMALS_SELECT = "SELECT * FROM " + DB_ANIMALS;
    private static final String DB_ANIMALS_SELECT_ID = "SELECT ID FROM " + DB_ANIMALS;
    private static final String DB_ANIMALS_ID = "ID_ANIMAL";
    private static final String DB_ANIMALS_NOM = "NOMBRE";
    private static final String DB_ANIMALS_ESPE = "ESPECIE";
    private static final String DB_ANIMALS_PELIGROSIDAD = "PELIGROSIDAD";
    private static final String DB_ANIMALS_PESO = "PESO";

    public void rellenarTablaVisitantes() {
        vaciarTablaPrincipal();
        try {
            ResultSet rs = DBManagerZoo.getTablaAnimals(DEFAULT_CURSOR, DISPOSE_ON_CLOSE);
            while (rs.next()) {
                int id = rs.getInt(DB_ANIMALS_ID);
                String nombre = rs.getString(DB_ANIMALS_NOM);
                String especie = rs.getString(DB_ANIMALS_ESPE);
                float peso = rs.getFloat(DB_ANIMALS_PESO);

                DefaultTableModel model = (DefaultTableModel) jTablePanelVisitante.getModel();
                Object[] row = {id, nombre, especie, peso};
                model.addRow(row);

            }
            rs.close();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    //método para lanzar un proceso, en este caso busca el nombre de la especie en wikipedia
    public static void LanzarProgEXE(String[] ruta) {
        try {
            ProcessBuilder pb = new ProcessBuilder(ruta);
            Process p = pb.start();
        } catch (IOException ex) {
            System.out.println("error");
        }

    }

    public void vaciarTablaPrincipal() {

        //vaciamos la tabla recorriendola con un bucle for
        DefaultTableModel tb = (DefaultTableModel) jTablePanelVisitante.getModel();
        int a = jTablePanelVisitante.getRowCount() - 1; //contamos las filas
        //bucle para borrar todas las filas
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePanelVisitante = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonMostrarAnimales = new javax.swing.JButton();
        jButtonSalirVisitante = new javax.swing.JButton();
        jButtonCerrarVisitante = new javax.swing.JButton();
        jLabelUsuarioSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(797, 576));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTablePanelVisitante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Especie", "Peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePanelVisitante);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Jurassic Park", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jurassic  Zoo  @");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonMostrarAnimales.setBackground(new java.awt.Color(103, 0, 3));
        jButtonMostrarAnimales.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jButtonMostrarAnimales.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMostrarAnimales.setText("Mostrar Animal");
        jButtonMostrarAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMostrarAnimalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMostrarAnimalesMouseExited(evt);
            }
        });
        jButtonMostrarAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarAnimalesActionPerformed(evt);
            }
        });

        jButtonSalirVisitante.setBackground(new java.awt.Color(103, 0, 3));
        jButtonSalirVisitante.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jButtonSalirVisitante.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalirVisitante.setText("Salir");
        jButtonSalirVisitante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirVisitanteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalirVisitanteMouseExited(evt);
            }
        });
        jButtonSalirVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirVisitanteActionPerformed(evt);
            }
        });

        jButtonCerrarVisitante.setBackground(new java.awt.Color(103, 0, 3));
        jButtonCerrarVisitante.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jButtonCerrarVisitante.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCerrarVisitante.setText("Cerrar Sesión");
        jButtonCerrarVisitante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCerrarVisitanteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCerrarVisitanteMouseExited(evt);
            }
        });
        jButtonCerrarVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarVisitanteActionPerformed(evt);
            }
        });

        jLabelUsuarioSesion.setBackground(new java.awt.Color(255, 255, 255));
        jLabelUsuarioSesion.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jLabelUsuarioSesion.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUsuarioSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUsuarioSesion.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(320, 320, 320)
                                .addComponent(jButtonMostrarAnimales))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabelUsuarioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonCerrarVisitante)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonSalirVisitante)))))
                        .addGap(0, 314, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalirVisitante)
                    .addComponent(jButtonCerrarVisitante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsuarioSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButtonMostrarAnimales)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarAnimalesActionPerformed
        
        int SelectedRow = jTablePanelVisitante.getSelectedRow();

        String name = (String) jTablePanelVisitante.getValueAt(SelectedRow, 2);

        String[] ruta = {"C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe", "https://es.wikipedia.org/wiki/" + name};
        LanzarProgEXE(ruta);
    }//GEN-LAST:event_jButtonMostrarAnimalesActionPerformed

    private void jButtonSalirVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirVisitanteActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSalirVisitanteActionPerformed

    private void jButtonCerrarVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarVisitanteActionPerformed
        this.dispose();
        Login.LoginUser open = new Login.LoginUser();
        open.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarVisitanteActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_formMouseDragged

    private void jButtonCerrarVisitanteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarVisitanteMouseEntered
        jButtonCerrarVisitante.setCursor(new Cursor(HAND_CURSOR));
        jButtonCerrarVisitante.setBackground( new Color(217,165,9));
        jButtonCerrarVisitante.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButtonCerrarVisitanteMouseEntered

    private void jButtonCerrarVisitanteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarVisitanteMouseExited
        jButtonCerrarVisitante.setBackground( new Color(103,0,3));
        jButtonCerrarVisitante.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonCerrarVisitanteMouseExited

    private void jButtonSalirVisitanteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirVisitanteMouseEntered
        jButtonSalirVisitante.setCursor(new Cursor(HAND_CURSOR));
        jButtonSalirVisitante.setBackground( new Color(217,165,9));
        jButtonSalirVisitante.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButtonSalirVisitanteMouseEntered

    private void jButtonSalirVisitanteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirVisitanteMouseExited
        jButtonSalirVisitante.setBackground( new Color(103,0,3));
        jButtonSalirVisitante.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonSalirVisitanteMouseExited

    private void jButtonMostrarAnimalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMostrarAnimalesMouseEntered
        jButtonMostrarAnimales.setCursor(new Cursor(HAND_CURSOR));
        jButtonMostrarAnimales.setBackground( new Color(217,165,9));
        jButtonMostrarAnimales.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButtonMostrarAnimalesMouseEntered

    private void jButtonMostrarAnimalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMostrarAnimalesMouseExited
        jButtonMostrarAnimales.setBackground( new Color(103,0,3));
        jButtonMostrarAnimales.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonMostrarAnimalesMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Panel_Visitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Panel_Visitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Panel_Visitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Panel_Visitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Panel_Visitante().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarVisitante;
    private javax.swing.JButton jButtonMostrarAnimales;
    private javax.swing.JButton jButtonSalirVisitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUsuarioSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePanelVisitante;
    // End of variables declaration//GEN-END:variables
}
